create user 'user-db1'@'%' identified by '1234';

grant all privileges on *.* to 'user-db1'@'%';

flush privileges;

create database int365;

use int365;

DROP TABLE IF EXISTS NEWS ;
DROP TABLE IF EXISTS REPORT;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS GROUP_TARGET;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS EDUCATION_LEVEL;
DROP TABLE IF EXISTS CHAT_HISTORY;
DROP TABLE IF EXISTS CHAT;

CREATE TABLE CHAT(
  CHAT_ID INT NOT NULL AUTO_INCREMENT,
  NAME_1 VARCHAR(100) NOT NULL,
  NAME_2 VARCHAR(100) NOT NULL,
  CREATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (CHAT_ID)
);

CREATE TABLE CHAT_HISTORY(
  HISTORY_ID INT NOT NULL AUTO_INCREMENT,
  CHAT_ID INT NULL,
  MESSAGE VARCHAR(250) NOT NULL,
  SENDER_NAME VARCHAR(100) NOT NULL,
  RECEIVER_NAME VARCHAR(100) NULL,
  SENT_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (HISTORY_ID),
  FOREIGN KEY (CHAT_ID) REFERENCES CHAT (CHAT_ID)
);

CREATE TABLE NEWS (
    NEW_ID INT NOT NULL AUTO_INCREMENT,
    TITLE  VARCHAR(200) NOT NULL,
    DETAIL VARCHAR(1000) NOT NULL,
    THUMBNAIL_PATH VARCHAR(100) NULL,
    THUMBNAIL_FILE_NAME VARCHAR(100) NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    CREATE_BY VARCHAR(60) NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    UPDATE_BY VARCHAR(60) NOT NULL,
    PRIMARY KEY (NEW_ID)
);

CREATE TABLE REPORT (
    REPORT_ID INT NOT NULL AUTO_INCREMENT,
    TOPIC VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (REPORT_ID)
);

CREATE TABLE USER(
    USER_ID INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(30) NOT NULL,
    TITLE_NAME_TH VARCHAR(20) NOT NULL,
    FIRST_NAME_TH VARCHAR(60) NOT NULL,
    LAST_NAME_TH VARCHAR(80) NOT NULL,
    ROLES VARCHAR(120) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE SUBJECT(
   SUBJECT_ID INT NOT NULL AUTO_INCREMENT,
   SUBJECT_NAME VARCHAR(100) NOT NULL,
   PRIMARY KEY (SUBJECT_ID)
);

CREATE TABLE EDUCATION_LEVEL(
  ED_ID INT NOT NULL AUTO_INCREMENT,
  ED_NAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (ED_ID)
);

CREATE TABLE GROUP_TARGET(
  GROUP_ID INT NOT NULL AUTO_INCREMENT,
  GROUP_NAME VARCHAR(100) NOT NULL,
  SUBJECT_ID INT NOT NULL,
  ED_ID INT NOT NULL,
  PRIMARY KEY (GROUP_ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID),
  FOREIGN KEY (ED_ID) REFERENCES EDUCATION_LEVEL (ED_ID)
);

CREATE TABLE QUESTION(
  Q_ID INT NOT NULL AUTO_INCREMENT,
  QUESTION VARCHAR(300) NOT NULL,
  ANSWER VARCHAR(600) NOT NULL,
  GROUP_ID INT NOT NULL,
  YEAR VARCHAR(4) NOT NULL,
  PRIMARY KEY (Q_ID),
  FOREIGN KEY (GROUP_ID) REFERENCES GROUP_TARGET (GROUP_ID)
);