name: backend
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/int-365-project/backend:latest

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATEKEY }}
        port: ${{ secrets.SERVERPORT }}
        script: |
          export TOKEN=${{ secrets.INT365 }}
          export GITHUB_USER=62130500093
          echo $TOKEN | docker login ghcr.io --password-stdin --username $GITHUB_USER
          cd ./Backend
          docker-compose stop && docker-compose rm -f
          docker-compose pull
          docker-compose up -d
          docker image prune -af